### PR TITLE
Fallback to any language, if value exists

### PR DESCRIPTION
**Pull request by raratiru**
Created a test for what is proposed in #13.

It seems decent -although opinionated- when everything else has failed, to search for any value in all available languages. Nonetheless, it is all happening in the context of a Fall Back Solution.

### CODE REVIEW

**Comment by raratiru** [comment]
Unfortunately, I run on Debian (python 3.5) and black is not available for this version.

**Comment by matthiask** [comment]
Thank you! (Don't worry about black etc. -- it's good to formulate expectations, but I wouldn't block a merge just because of this, fixing things after merging is fine.)

This probably makes sense for scenarios where you e.g. have users filling in content in different languages and you'd rather show anything than nothing at all. 

I think `fallback_to_default` is a bad name for this though because a fallback language does not exist anymore. Maybe `fallback_to_any`? I experimented a bit with this idea in this branch: https://github.com/matthiask/django-translated-fields/compare/mk/fallback-to-any

I'm having a bit of a hard time deciding whether this would be a good addition to the code of this library or if something like this is better suited as another example in the documentation. Please don't read this as a rejection of this pull request, it's more me thinking out loud here. 

(Side note: It's a bit ugly that overriding `languages` is supported but the getters and setters always use the global `settings.LANGUAGES` list. I experimented a bit more here: https://github.com/matthiask/django-translated-fields/compare/mk/field-argument but somehow the cure feels worse than the problem...)

**Comment by raratiru** [comment]
Thank you for the feedback!

Indeed, fallback_to_any, by default includes the first language which it is arbitrarily called "the default" and it relieves from the burden of explaining the special value of the first language in the list! 

The best way to avoid prematurely optimizing, could be to abide by a strong criterion. The deal with fallback_to_any is that it will do its best to reveal the available information, even in another language. 

It is most probable that the person who was typing-in the data, filled the wrong field or just omitted the right field. Validation error was not raised because the field is not required -for other reasons- and there it is: 

A legitimate user did not find the information which still was available even though it was not well shaped. Isn't it better to ask for forgiveness of mis-revealing than asking for permission to reveal an already asked and surely available info?

Putting it in the docs, is descent. Building it in, will offer some magic, which in small portions could be a pleasant surprise.
```python

return current or next(
    filter(
        None,
        (getattr(self, to_attribute(name, language)) for language in languages),
    ),
    '',  # Added a default value to avoid StopIteration if all fields are left blank.
)
```
This is a piece of art `<del>`! 

I understand the sidenote, it is not ugly, it just brings a relatively big change for a balance:  It decouples the library from django settings. 

I have not grasped the real meaning of overriding the `languages` in instantiation  of the field, yet. I have to use it more!

**Comment by raratiru** [comment]
I am closing this PR since it is already taken into consideration.

**Comment by matthiask** [comment]
I merged the `fallback_to_any` branch, this feature will land in the next release!

**Comment by raratiru** [comment]
Thank you, this is great news!

**Pull request closed without merging**
