### PR TITLE
Add lazyness to language_code_formfield_callback

### PR DESCRIPTION
**Pull request by Tom-Hubrecht**
Currently, if we want to use `language_code_formfield_callback` in a ModelForm, the label is not translated before adding the language code, by adding a lazy version, the label can be translated on the fly according to the user's language setting.

### CODE REVIEW

**Comment by matthiask** [comment]
Hi @Tom-Hubrecht 

I think I like it. It would be great if you could add a sentence or two to the docs and add a test (if it is straightforward, at least). I'm not sure if the whole callback has to be lazy or whether it may be sufficient to "only" make `kwargs["label"]` lazy? Something like (completely untested!)

```
from django.utils.functional import keep_lazy_text
kwargs["label"] = keep_lazy_text(lambda: "%s [%s]" % (capfirst(db_field.verbose_name), language_code))
```

I think the default behavior could be changed in this case, and there wouldn't be a need for any changes to the docs. What do you think?

**Comment by Tom-Hubrecht** [comment]
Hi @matthiask

Indeed, it is enough to make `kwargs["label"]` lazy, and I changed the form test to reflect the modification.

**Comment by matthiask** [comment]
Great, thanks!

**Comment by matthiask** [comment]
I've released 0.11.1 containing this fix.

**Pull request merged**
