### PR TITLE
Update the verbose_name

### PR DESCRIPTION
**Pull request by gabn88**
So that every generated field is distinguishable by language.

Not sure if you want to accept it, but it would make sense I think?

### CODE REVIEW

**Comment by gabn88** [comment]
Of course the tests would have to be changed too, but I first would like to know if you're open for such a change. It would render the TranslatedAdmin mixin useless. But I think I like it.

**Comment by matthiask** [comment]
Thank you! I had something like this in there but dropped it later because the language code is often redundant (except when it's not)

Here's the removal of the feature:
https://github.com/matthiask/django-translated-fields/commit/2c3266d0b5c410878329defc95ca373343b47501#diff-f21982c42cd2a8745f85257c962c300cL74

The language code is very useful (essential, even) in the administration interface. The `translated_fields.admin.TranslatedFieldAdmin` mixin helps with this case.

Or maybe you have a different use case in mind?

**Comment by gabn88** [comment]
I have some forms which I create dynamically. I use the verbose_name for the label of the form. 
Of course I could change all the forms to generate the label, but this looks like something that could be incorporated on a higher level.

**Comment by gabn88** [comment]
Why was the feature removed?

**Comment by matthiask** [comment]
Yes I see. 

I'm also using the `verbose_name` in the frontend but in my case it's important that the language code isn't shown (example: the "In Words" section of https://www.fcz.ch/en/first-team/squad/yanick-brecher/ )

--- 

Why was it removed? Because the admin class offers the same thing while keeping the `verbose_name` modification localized to the administration interface. It's more explicit and removing code is always good (if it's possible)

Would this work for you? You'd have to specify the `formfield_callback` in your form definitions and `modelform_factory` calls but it would still be explicit: https://github.com/matthiask/django-translated-fields/commit/9f075101cd1d8f810267ea1cafbfb6e7bbcfb784

**Comment by gabn88** [comment]
See [here for how to address this](https://github.com/matthiask/django-translated-fields/commit/9f075101cd1d8f810267ea1cafbfb6e7bbcfb784)

**Pull request closed without merging**
